driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-13.2
  - name: opensuse-leap
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-server-2012r2-standard
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list: perl_test::default
