driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: windows-server-2012r2-standard
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list: perl_test::default
