driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-server-2012r2-standard
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list: perl_test::default
